definitions:
  http.ApiResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        description: success | fail
        type: string
    type: object
  http.CreateContainerRequest:
    properties:
      command:
        example:
        - '''/bin/sh'''
        - '''-c'''
        - '''echo hello; sleep 60'''
        items:
          type: string
        type: array
      image:
        example: alpine
        type: string
    type: object
  http.ExecContainerRequest:
    properties:
      command:
        example:
        - '''/bin/sh'''
        - '''-c'''
        - '''echo hello'''
        items:
          type: string
        type: array
      interactive:
        example: true
        type: boolean
    type: object
  http.StartContainerRequest:
    properties:
      interactive:
        example: true
        type: boolean
    type: object
info:
  contact: {}
paths:
  /v1/containers:
    post:
      consumes:
      - application/json
      description: create a new container
      parameters:
      - description: Container Spec
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.CreateContainerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.ApiResponse'
      summary: Create a container
      tags:
      - containers
  /v1/containers/{containerId}/actions/delete:
    delete:
      description: delete an exitsting container
      parameters:
      - description: Container ID
        in: path
        name: containerId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.ApiResponse'
      summary: delete a container
      tags:
      - containers
  /v1/containers/{containerId}/actions/exec:
    post:
      description: execute command inside an exitsting container
      parameters:
      - description: Container ID
        in: path
        name: containerId
        required: true
        type: string
      - description: Execute Options
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.ExecContainerRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.ApiResponse'
      summary: exec a container
      tags:
      - containers
  /v1/containers/{containerId}/actions/start:
    post:
      description: start an exitsting container
      parameters:
      - description: Container ID
        in: path
        name: containerId
        required: true
        type: string
      - description: Start Options
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.StartContainerRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.ApiResponse'
      summary: start a container
      tags:
      - containers
  /v1/containers/{containerId}/actions/stop:
    post:
      description: stop an exitsting container
      parameters:
      - description: Container ID
        in: path
        name: containerId
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.ApiResponse'
      summary: stop a container
      tags:
      - containers
  /v1/hooks/droplet:
    post:
      description: apply hook from droplet
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.ApiResponse'
      summary: apply hook
      tags:
      - Hooks
swagger: "2.0"
